os: osx
osx_image: xcode10.2
language: swift

before_cache:
  - cocoacache save --podfile Example/Podfile.lock 
cache:
  bundler: true 
  directories:    
    - Specs
install:  
  - bundle install
  - cocoacache restore --podfile Example/Podfile.lock 
  - cd Example; bundle exec pod check || (bundle exec pod install --repo-update); cd ..; # use () to group commands together to run if `pod check`
env:
  global:
    # COCOAPODS_TRUNK_TOKEN - access token to deploy to cocoapods.
    - secure: "ZL0zY1sRz29Fb25KUyXYWxVhyTUqWWu97/WT3hrNtL+xbA0TK7O6Pee9gu2Xtinj9Ca2MVhjHsRQkM7sXk2NYaYhrM+/VbXefc7VcbhslgQcqq8QtP4InQqOH0fn0Qf6gT4eDfoR58dY7b3/wkNB4qwp0/5cHA0955hBFSrF9d28ctz9+w0+ZRMNitLkcu7n3BSKx1z93ANwjukGAGQ2AHrDAhZASWOSQ3hGUSLuUmal25VlWrUo0yVL6g5yt5QYHiJrCtE/+a6zT2KIJA0EYZZO3q3LOYrQy3bcR7WLLJnR2dYbH01AqzJ7QEpoxGAQ4KZCzw1PoVdycsg9ysX71A53VMLpN9Yz0XoFGa6ln8HOQTS1iiw6JBexm+2Tik1TjblTs2kiQwnLoZlfJ18/gDRFwaeKReXi0La+SqwmSDiZDJQsx6DkH0qSB7vDJaASGMONDhYj3jho8gg8eYs/kJRIb8g3ieO4VPuKVNodbMOdqU+AtN6MNxRddVM1HH5tms5O89t3ipKY8Vnl2RPRBm4u4wJCO+ZR0W+5JKdBxocPF7KniDX6fcO9XjnL2+2T3q/OKxjfX4g6jijHVW8I/m7n7H1iZ39uy/plXTiqKHG9IvJRYjydk3ybh6Nf/QvLbzL4EUe724pbrBIMLPjletOJ9iwJGmyNmI+UjVoou+U="    

jobs:
  include:
  - stage: tests
    script: ruby scripts/run_unit_tests.rb
  - stage: pull-request
    script: ruby scripts/pull_request.rb
  - stage: deploy
    script: ruby scripts/deploy.rb

stages:
  - name: tests
    if: type IN (pull_request, push) AND tag IS blank
  - name: pull-request
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present