os: osx
osx_image: xcode10.2
language: swift

before_cache:
  - cocoacache save --podfile Example/Podfile.lock 
cache:
  bundler: true 
  directories:    
    - Specs
install:  
  - bundle install
  - cocoacache restore --podfile Example/Podfile.lock 
  - cd Example; bundle exec pod check || (bundle exec pod install --repo-update); cd ..; # use () to group commands together to run if `pod check`
env:
  global:
    # COCOAPODS_TRUNK_TOKEN - access token to deploy to cocoapods.
    - secure: "sPMM+zVNWuXtz3N7ciwl+RqWdlPSRWzRrsoa6eVeTNpg/Zds2vmYWPuvDHXrz696QwetYl+vmYlqjN7rN1lLD5rGfjlI+Hf/N4fuOa4hnSue3OhrNAgLiOd7/FjKM0EdzSZ+d3w50Z75KQVgTKyCgwGlD48GN/P+91orcNDKCSxprD65HFSJGjot3E0W4urKlwhQ4v0CmR8ren3wtdJ2gcoeLf/m/YFbrI/20r6k/moc9UKUUn8gLslPxU2EvS3nH93nsC7Gf3XeHOAwXXQpZEhGvUeVLewTZ1I5Ql2Ktw+9mt8BJ7u97m3JN+ho6jZtR9PvL3qmVskNpzvwsoVx+mpx2V2aLuxtlr3kEkRUtzniWJ9f6aOZtdxDV0JwWRgClnzQHY835gTs4TPNi648g6eX01w3/kuEWJeCibQPR05qhy+cctwJXOQ0sRE/agxS3WD0ia3hTG8X7cjajJ2LiPh8/djjsfVPMYGrmx9bh/fLPuEHtRJqwcBUvPI++x6FA+kmXAit6497x8Zf9PG3PCyHLpn4nrTddFlvLvNQTEljmLjfxcBTumXt9feiJa5U3ylZj4KbVzFPiIhPuLPPPqZAzbE/WkVzgRQ9/TpU2Z2RSRnYNN/0VoxzfL3djeLpOvA+Ep6b8cjIEzYfPH+2Tazs/YlP1hQNdw0Q0XA7De4="

jobs:
  include:
  - stage: tests
    script: ruby scripts/run_unit_tests.rb
  - stage: pull-request
    script: ruby scripts/pull-request.rb
  - stage: deploy
    script: ruby scripts/deploy.rb

stages:
  - name: tests
    if: type IN (pull_request, push) AND tag IS blank
  - stage: pull-request
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present