os: osx
osx_image: xcode10.2
language: swift

before_cache:
  - cocoacache save --podfile Example/Podfile.lock 
cache:
  bundler: true 
  directories:    
    - Specs
install:  
  - bundle install
  - cocoacache restore --podfile Example/Podfile.lock 
  - cd Example; bundle exec pod check || (bundle exec pod install --repo-update); cd ..; # use () to group commands together to run if `pod check`
env:
  global:
    # COCOAPODS_TRUNK_TOKEN - access token to deploy to cocoapods.

jobs:
  include:
  - stage: tests
    script: ruby scripts/run_unit_tests.rb
  - stage: pull-request
    script: ruby scripts/pull_request.rb
  - stage: deploy
    script: ruby scripts/deploy.rb

stages:
  - name: tests
    if: type IN (pull_request, push) AND tag IS blank
  - name: pull-request
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present
