osx_image: xcode11.5
language: swift

cache: cocoapods
podfile: Example/Podfile

env:
  global:
    # COCOAPODS_TRUNK_TOKEN - access token to deploy to cocoapods. 
    # GITHUB_TOKEN - github user with collaborative status to repo. github token with push access to git repo. 

jobs:
  include:  
    - stage: tests
      script: 
        - cd Example && gem install fastlane && fastlane scan && cd ..
    - stage: lint
      script: 
        # lint commits to make sure they are conventional 
        - nvm install lts/*; npm i @commitlint/cli @commitlint/config-conventional @commitlint/travis-cli; npx commitlint-travis; 
        - pod lib lint --allow-warnings
    - stage: deploy
      script: 
        # Use nvm to install and use the Node LTS version (nvm is installed on all Travis images)
        - nvm install lts/*; npm i semantic-release-cocoapods @semantic-release/git @semantic-release/changelog; npx semantic-release;
    - stage: pod-deploy
      script:
        - pod trunk push

stages:
  - name: lint
    if: type IN (push, pull_request) AND tag IS blank   
  - name: tests
    if: type IN (push, pull_request) AND tag IS blank   
  - name: deploy
    if: type IN (push) AND branch IN (master, beta, alpha)
  - name: pod-deploy
    if: tag IS present